<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="58276" started-at="2020-08-12T16:30:26Z" finished-at="2020-08-12T16:31:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58276" started-at="2020-08-12T16:30:26Z" finished-at="2020-08-12T16:31:24Z">
      <class name="org.amazon.testcases.TC001_ValidateLogin">
        <test-method status="PASS" signature="setdata()[pri:0, instance:org.amazon.testcases.TC001_ValidateLogin@731a74c]" name="setdata" is-config="true" duration-ms="6" started-at="2020-08-12T22:00:26Z" finished-at="2020-08-12T22:00:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setdata -->
        <test-method status="PASS" signature="getDesiredCapabilites()[pri:0, instance:org.amazon.testcases.TC001_ValidateLogin@731a74c]" name="getDesiredCapabilites" is-config="true" duration-ms="4" started-at="2020-08-12T22:00:26Z" finished-at="2020-08-12T22:00:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDesiredCapabilites -->
        <test-method status="FAIL" signature="testlogin()[pri:0, instance:org.amazon.testcases.TC001_ValidateLogin@731a74c]" name="testlogin" duration-ms="58258" started-at="2020-08-12T22:00:26Z" finished-at="2020-08-12T22:01:24Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at org.amazon.testcases.TC001_ValidateLogin.testlogin(TC001_ValidateLogin.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
      </class> <!-- org.amazon.testcases.TC001_ValidateLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
